### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by qiuzi** [lefoyer/ndpi-netfilter#1]
With the latest ndpi compatible?

PS:Support openwrt do?

**Comment by lefoyer** [comment]
Yes. But most of the protocols is not defined.

**Comment by qiuzi** [comment]
What protocols?
xt_ndpi.h？.I want to install in the opewnrt

**Comment by lefoyer** [comment]
I am not test on openwrt.
My mail to ntop-dev list:

I am update ndpi-netfilter for NDPI master
https://github.com/lefoyer/ndpi-netfilter

but some protocol not blocked

chain added in first line in FORWARD

Chain NDPI (1 references)
 pkts bytes target     prot opt in     out     source               destination
   39  1716 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol TeamViewer  reject-with icmp-port-unreachable
    0     0 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol HTTP_Proxy  reject-with icmp-port-unreachable
    0     0 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol HTTP_Connect_SSL_over_HTTP  reject-with icmp-port-unreachable
    0     0 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol Gmail  reject-with icmp-port-unreachable
    0     0 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol YouTube  reject-with icmp-port-unreachable
    4   228 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol DNS  reject-with icmp-port-unreachable
   72  4499 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol ICMP  reject-with icmp-port-unreachable
    0     0 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol FTP  reject-with icmp-port-unreachable
    7   330 REJECT     all  --  eth1   \*       0.0.0.0/0            0.0.0.0/0           protocol Skype  reject-with icmp-port-unreachable

TeamViewer - blocked
HTTP_Proxy - not blocked
HTTP_Connect_SSL_over_HTTP - not blocked
Gmail - not blocked
YouTube - not blocked
DNS - blocked
ICMP - not blocked
FTP - not blocked
Skype - not blocked (some packets detected? but skype login and worked)

**Comment by lefoyer** [comment]
You need port src/Makefile for compile on openwrt.

**Comment by qiuzi** [comment]
#

# Copyright (C) 2010 OpenWrt.org

#

# This is free software, licensed under the GNU General Public License v2.

# See /LICENSE for more information.

#

include $(TOPDIR)/rules.mk

PKG_NAME:=iptables-mod-ndpi
PKG_RELEASE:=2
PKG_VERSION:=1.$(PKG_RELEASE)
PKG_REV:=6225

PKG_SOURCE:=iptables-mod-ndpi-$(PKG_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=iptables-mod-ndpi-$(PKG_VERSION)
PKG_SOURCE_URL:=https://svn.ntop.org/svn/ntop/trunk/nDPI
PKG_SOURCE_VERSION:=$(PKG_REV)
PKG_SOURCE_PROTO:=svn

PKG_FIXUP:=autoreconf

include $(INCLUDE_DIR)/package.mk
include $(INCLUDE_DIR)/kernel.mk

define Package/iptables-mod-ndpi
    SUBMENU:=Firewall
    SECTION:=net
    CATEGORY:=Network
    TITLE:=ndpi successor of OpenDPI
    URL:=http://www.ntop.org/products/ndpi/
    DEPENDS:=+iptables +iptables-mod-conntrack-extra +kmod-ipt-ndpi
    MAINTAINER:=Thomas Heil heil@terminal-consulting.de
endef

define Package/iptables-mod-ndpi/description
    nDPI is a ntop-maintained superset of the popular OpenDPI library
endef

define Download/ndpi-netfilter
    VERSION:=854f4e4af11d0ed0a98221622a96c370db464d56
    FILE:=ndpi-netfilter-$(PKG_VERSION).tar.gz
    URL:=https://github.com/lefoyer/ndpi-netfilter.git
    PROTO:=git
    SUBDIR:=ndpi-netfilter
endef

define Build/Prepare
    $(call Build/Prepare/Default)
    $(eval $(call Download,ndpi-netfilter))
    tar -zxvf $(DL_DIR)/ndpi-netfilter-$(PKG_VERSION).tar.gz -C $(PKG_BUILD_DIR)
endef

define Build/Configure
    (cd $(PKG_BUILD_DIR); \
    libtoolize --automake --force --copy; \
    autoreconf -ihv  || exit 1 \
    );

endef

CONFIGURE_ARGS += \
    --with-pic \
    --target=$(GNU_TARGET_NAME) \
    --host=$(GNU_TARGET_NAME) \
    --build=$(GNU_HOST_NAME) \
    LIBS=-lposix -lndpi_la-spotify.lo -lndpi_la-ahocorasick.lo 

MAKE_PATH := ndpi-netfilter

ifneq ($(CONFIG_USE_EGLIBC),)
    TARGET_CPPFLAGS += -I$(STAGING_DIR)/usr/include 
endif

MAKE_FLAGS += \
    KERNEL_DIR=$(LINUX_DIR) \
    NDPI_PATH=$(PKG_BUILD_DIR) \
    ARCH="$(LINUX_KARCH)" \
    CROSS_COMPILE="$(TARGET_CROSS)" \
    all

define Package/iptables-mod-ndpi/install
    $(INSTALL_DIR) $(1)/usr/lib/iptables
    $(INSTALL_BIN) $(PKG_BUILD_DIR)/ndpi-netfilter/ipt/libxt_ndpi.so $(1)/usr/lib/iptables
endef

define KernelPackage/ipt-ndpi
    SUBMENU:=Netfilter Extensions
    TITLE:= nDPI net netfilter module
    DEPENDS:=+kmod-ipt-compat-xtables
    KCONFIG:=CONFIG_NF_CONNTRACK \
    CONFIG_NF_CONNTRACK_EVENTS=y
FILES:= \
    $(PKG_BUILD_DIR)/ndpi-netfilter/src/xt_ndpi.ko
AUTOLOAD:=$(call AutoLoad,46,xt_ndpi)
endef

$(eval $(call BuildPackage,iptables-mod-ndpi))
$(eval $(call KernelPackage,ipt-ndpi))

Where is the need to change?

**Comment by lefoyer** [comment]
Ask in openwrt team.

> /home/fclql/trunk/build_dir/target-mipsel_uClibc-0.9.33.2/iptables-mod-ndpi-1.2/ ndpi-netfilter/src/ndpi_cpy
> /lib/ndpi_main.c:37:18: fatal error: time.h: No such file or directory

not found linux/time.h

**Comment by qiuzi** [comment]
Use https://github.com/heil/owrt-package/tree/master/net/iptables-mod-ndpi normal

**Comment by lefoyer** [comment]
if this https://github.com/heil/ndpi-netfilter version compiled normal, clone my repo to you git account and comment in src/Makefile

#EXTRA_CFLAGS := $(ccflags-y)
#MODULES_DIR := /lib/modules/$(shell uname -r)
#KERNEL_DIR := ${MODULES_DIR}/build

**Comment by qiuzi** [comment]
_cpy/lib/ndpi_main.c:37:18: fatal error: time.h: No such file or directory
 #include < time.h >
                  ^
compilation terminated.

src/Makefile

NDPI_PATH2 := ${NDPI_PATH}/src
NDPI_SRC := ndpi_cpy
NDPI_PRO := ${NDPI_SRC}/lib/protocols
NDPI_THIRD := ${NDPI_SRC}/lib/third_party/src

ccflags-y += -I${src}/${NDPI_SRC}/include -I${src}/${NDPI_SRC}/lib -I${src}/${NDPI_SRC}/lib/third_party/include -DOPENDPI_NETFILTER_MODULE

#EXTRA_CFLAGS := $(ccflags-y)
#MODULES_DIR := /lib/modules/$(shell uname -r)
#KERNEL_DIR := ${MODULES_DIR}/build

**Comment by lefoyer** [comment]
This https://github.com/heil/ndpi-netfilter version compiled normal ?

**Comment by qiuzi** [comment]
yes normal 
If he patch

**Comment by lefoyer** [comment]
if you comment in my Makefile this line 
#EXTRA_CFLAGS := $(ccflags-y)
#MODULES_DIR := /lib/modules/$(shell uname -r)
#KERNEL_DIR := ${MODULES_DIR}/build

all other identical (for make)
i am not understand while this not compiled in openwrt toolchain.

**Comment by qiuzi** [comment]
But the problem is ndpi_main.c: 37:18: fatal error: time.h: No such file or directory

compilation terminated.
The latest ndpi not compatible

**Comment by lefoyer** [comment]
file /lib/ndpi_main.c from NDPI not my ndpi-netfilter and in this file not any include time.h

download last nDPI to NDPI_PATH=$(PKG_BUILD_DIR)

**Comment by qiuzi** [comment]
The old NDPI support agreement can not match your
https://github.com/nyov/ndpi

**Comment by lefoyer** [comment]
My version ndpi-netfilter for nDPI 1.4 (svn co https://svn.ntop.org/svn/ntop/trunk/nDPI)

**Comment by qiuzi** [comment]
yes ,I use the latest

PKG_NAME:=iptables-mod-ndpi
PKG_RELEASE:=2
PKG_VERSION:=1.$(PKG_RELEASE)
PKG_REV:=6225

PKG_SOURCE:=iptables-mod-ndpi-$(PKG_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=iptables-mod-ndpi-$(PKG_VERSION)
PKG_SOURCE_URL:=https://svn.ntop.org/svn/ntop/trunk/nDPI
PKG_SOURCE_VERSION:=$(PKG_REV)
PKG_SOURCE_PROTO:=svn

**Comment by sermilrod** [comment]
I had an issue installing ndpi-netfilter. I got an undefined symbol warning that directly affects to xt_ndpi.ko file

This is the specific output of the error:

 CC [M]  /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/ndpi_cpy/lib/protocols/yahoo.o
  CC [M]  /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/ndpi_cpy/lib/protocols/zattoo.o
  LD [M]  /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/xt_ndpi.o
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: "ndpi_search_whois_das" [/usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/xt_ndpi.ko] undefined!
  CC      /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/xt_ndpi.mod.o
  LD [M]  /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/xt_ndpi.ko.unsigned
  NO SIGN [M] /usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src/xt_ndpi.ko
make[2]: Leaving directory `/usr/src/kernels/2.6.32-358.14.1.el6.x86_64'
rm -r ndpi_cpy
make[1]: Leaving directory`/usr/src/nDPI/ndpi-netfilter/ndpi-netfilter/src'

Could you give me a hand please?

Thanks in advance.
